auto_sync = false
command_chaining = true # Complete history after `&&` or `||`
dialect = "uk" # `atuin stats DATE` date format parsing
history_format = "{time}\t{duration}\t{command}"
inline_height = 20 # The interface's maximum number of lines
invert = true # Put the search bar at the top
prefers_reduced_motion = true # Don't live update timers
search_mode = "fuzzy" # prefix / fulltext / fuzzy / skim
style = "compact"
show_help = false
show_tabs = false # Don't show the bottom `Search | Inspect` tabs
update_check = false
workspaces = true # Enable git workspaces history

# cwd_filter = [
#   "^/very/secret/area",
# ]
# history_filter = [
#   "^secret-cmd",
#   "^innocuous-cmd .*--secret=.+",
# ]

[keymap.emacs]
"alt-backspace" = "delete-word-before"
"ctrl-a" = "cursor-start"

[stats]
common_prefix = ["sudo"]
common_subcommands = [
  "cargo",
  "doc", "docker",
  "git",
  "go",
  "ip",
  "jj",
  "k", "kubectl",
  "nix",
  "npm",
  "pod", "podman",
  "sc", "systemctl",
]
ignored_commands = [
  "cd",
  "e", "v",
  "l", "la", "ls",
]

[daemon] # Start with `atuin daemon`
enabled = true

[search]
filters = [ "global", "workspace", "directory", "host", "session"]

[sync]
records = true # Sync v2

[tmux]
# Disable the tmux popup for now. The popup forbids us to switch windows until it's closed.
enabled = false
